# Generated by Django 4.2.4 on 2023-08-15 14:49

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RaspberryShakeQuakes',
            fields=[
                ('code', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('depth', models.DecimalField(decimal_places=6, max_digits=15)),
                ('mag', models.DecimalField(decimal_places=6, max_digits=8)),
                ('timestamp', models.DateTimeField()),
                ('agency', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('loc_pnt', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'rs_quakes',
            },
        ),
        migrations.CreateModel(
            name='RaspberryShakeStations',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('elev', models.DecimalField(decimal_places=3, max_digits=10)),
                ('online', models.BooleanField(default=False)),
                ('acc', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('vel', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('disp', models.DecimalField(decimal_places=8, max_digits=15, null=True)),
                ('timestamp', models.DateTimeField()),
                ('address', models.TextField(null=True)),
                ('loc_pnt', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'rs_stations',
            },
        ),
    ]
